#!/bin/bash

export LC_ALL="C"

export OF_MAINTAINER="yoneLLR"
export FOX_BUILD_TYPE="Stable"
export FOX_VERSION="R11.1_1"
export FOX_VARIANT="XOS"

export FOX_TARGET_DEVICES="X689B,X689D,X689,Infinix-X689B,Infinix-X689D,Infinix-X689"
export TARGET_DEVICE_ALT="X689D,X689,Infinix-X689D,Infinix-X689"

export FOX_AB_DEVICE=1
export FOX_VIRTUAL_AB_DEVICE=1

export OF_NO_TREBLE_COMPATIBILITY_CHECK=1
export OF_USE_GREEN_LED=0
export OF_FLASHLIGHT_ENABLE=0
export OF_DISABLE_OTA_MENU=1
export OF_ALLOW_DISABLE_NAVBAR=0

export OF_SKIP_MULTIUSER_FOLDERS_BACKUP="1"
export OF_QUICK_BACKUP_LIST="/boot;/data;"

export FOX_DELETE_MAGISK_ADDON=1
export FOX_DELETE_AROMAFM=1
export FOX_REMOVE_AAPT=1

export FOX_ENABLE_APP_MANAGER=1
export OF_ENABLE_LPTOOLS=1

export FOX_ASH_IS_BASH=1
export FOX_USE_BASH_SHELL=1
export FOX_USE_NANO_EDITOR=1
export FOX_USE_TAR_BINARY=1
export FOX_USE_SED_BINARY=1
export FOX_USE_XZ_UTILS=1

export OF_SCREEN_H=2460
export OF_STATUS_H=105
export OF_STATUS_INDENT_LEFT=52
export OF_STATUS_INDENT_RIGHT=52
export OF_CLOCK_POS=1